Bugfix/ff prep refactored broken
wwf-ff/ForestForesight pull request #28
Opened 2024-11-12 10:16 UTC by ZillahCalle

2024-11-12 13:12 UTC, maasva requested changes
Hey Zillah! 
Most of the changes look good! However, there are some issues. The 2 most important ones are the following:
1. The changes made some of the test cases fail (depending on the function this can be due to the function name or interface changing.) 
2. Be careful when renaming variables that you rename *every* instance of them. For instance, there is still one instance of has_ground_truth that is still named hasgroundtruth which leads to an error. 
you should be able to find the errors relatively easily by running the tests and checking the ones that fail. If you want some assistance to do this, you'll know where to find me. 
Maas

2024-11-13 12:25 UTC, maasva commented on tests/testthat/test-initialize_shape_from_borders.R
Why did you choose to delete this test?

2024-11-13 12:31 UTC, ZillahCalle commented on tests/testthat/test-initialize_shape_from_borders.R
I still have this one left: 
Error (test-prepare_raster_data_by_tile.R:43:3): prepare_raster_data_by_tile works with shrink set to 'crop'
Error: [writeRaster] path does not exist

I removed the test because I also removed the function. It was useless because you would never use that function if you passed the preconditions in ff_prep.

2024-11-15 14:03 UTC, maasva approved these changes

2024-11-15 14:07 UTC, merged